apiVersion: skaffold/v2beta18
kind: Config

profiles:
  - name: dev
    build:
      local:
        push: true
      artifacts:
        - image: oscka/sample-api
          jib:
            args:
              - -DskipTests
              - "-Djib.container.environment=SPRING_PROFILES_ACTIVE=dev"           
            fromImage: eclipse-temurin:17.0.2_8-jre

